[tool.poetry]
name = "testing-de"
version = "0.1.0"
description = ""
authors = ["chernyshev"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
psycopg2 = "^2.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
